### ISSUE TITLE
Greenhouse gasses to list

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#11]
4/1

1. Do we list all greenhouse gasses (CARBON DIOXIDE (006),CARBON MONOXIDE (005),METHANE (004),NITROGEN OXIDES (NO+NO2) (002),NITROUS OXIDE (007)) for C increments and other variables, or do these just apply to aboveground biomass?

**5 gases are applicable to be selected in case of having carbon stock of biomass and dead organic matter expressed in tones dm/ha. This corresponds to the default values providers in Table 2.4 of ch.4 of the 2006 IPCC Gls.**

**Comment by teixeirak** [comment]
from KAT: Do you want all these gasses listed for ∆C (ForC’s delta.agb or NEE) as well, or just for C stock/ biomass variables? (I understand the logic for the stocks, but not sure if it applies to increments as well.)

from Valentyna: CO2 only for C fluxes. 5 gases are for C stock. 

___
@ValentineHerr , please update the code to list CO2 only (not multiple greenhouse gases) for fluxes and increments.

**Comment by ValentineHerr** [comment]
Currently, for `Gases (ID1,ID2,...)` I have : 

 **IF** 

`IPCC.Unit_.ID.` of [ForC_variables_mapping.csv](https://github.com/forc-db/IPCC-EFDB-integration/blob/main/doc/ForC-EFDB_mapping/ForC_variables_mapping.csv) is in Carbon units (if there is a "C" in the field)

**THEN**
enter `"CARBON DIOXIDE (006)"`

**OTHERWISE**

enter `"CARBON DIOXIDE (006),CARBON MONOXIDE (005),METHANE (004),NITROGEN OXIDES (NO+NO2) (002),NITROUS OXIDE (007)"`



@teixeirak, you are saying that the **IF** statement should be:
"if units is in carbon AND variable is a flux or increment"? 

OR, maybe more straightforward, if units are in Organic matter and variable is a stock, then enter  `"CARBON DIOXIDE (006),CARBON MONOXIDE (005),METHANE (004),NITROGEN OXIDES (NO+NO2) (002),NITROUS OXIDE (007)"`

**Comment by teixeirak** [comment]
It should be 

**IF** units are in Organic matter and variable is a stock, 
then enter "CARBON DIOXIDE (006),CARBON MONOXIDE (005),METHANE (004),NITROGEN OXIDES (NO+NO2) (002),NITROUS OXIDE (007)"

**ELSE** 
enter "CARBON DIOXIDE (006)"

**Comment by ValentineHerr** [comment]
Ok I integrated that in the script and updated the mapping document. I think we can close this.
