### ISSUE TITLE
ensure that ANPP_woody_stem records show up in the variables table

### ISSUE THREAD

**Issue by teixeirak** [forc-db/IPCC-EFDB-integration#43]
@ValentineHerr , I noticed that there are no records for ANPP_woody_stem in [this table](https://github.com/forc-db/IPCC-EFDB-integration/blob/main/doc/manuscript/figures_tables/C_variables.csv), although we've definitely sent some (e.g., Piponiot study). The problem may be that the table is not up to date (#42 ) or that I'm expecting ANPP_woody_stem records to show up as part of ANPP_woody (lumping for simplicity). I the problem is the latter, could you please adjust code such that these show up as part of ANPP_woody?

**Comment by teixeirak** [comment]
AGB or Classified otherwise (OTH) would be broader categories. I think the issue is just that ForC makes a fairly fine distinction between ANPP_woody and ANPP_woody_stem that I'm dropping for the purposes of this paper. I think that at some point your code just pulls ANPP_woody and doesn't pull in ANPP_woody_stem.

**Comment by ValentineHerr** [comment]
ok I look into this more carefully

**Comment by ValentineHerr** [comment]
OK, the following variable are filtered out because the script only looks at variables listed in [this file](https://github.com/forc-db/IPCC-EFDB-integration/blob/main/doc/manuscript/figures_tables/C_variables_order_template.csv). 
Can you tick the variables that should not be dropped and should be lumped into another?

 - [ ] NEE  
 - [ ] NEE_cum  
 - [ ] NEP  
 - [ ] GPP  
 - [ ] GPP_cum  
 - [ ] TBCF  
 - [ ] NPP_1  
 - [ ] NPP_2  
 - [ ] NPP_3  
 - [ ] NPP_4  
 - [ ] NPP_5  
 - [ ] NPP_0  
 - [ ] NPP_woody  
 - [ ] NPP_understory  
 - [ ] NPP_litter  
 - [ ] ANPP_1  
 - [ ] ANPP_2  
 - [ ] ANPP_0  
 - [ ] ANPP_woody  
 - [ ] ANPP_woody_stem  
 - [ ] ANPP_woody_branch  
 - [ ] ANPP_foliage  
 - [ ] ANPP_litterfall_1  
 - [ ] ANPP_litterfall_2  
 - [ ] ANPP_litterfall_0  
 - [ ] ANPP_repro  
 - [ ] ANPP_folivory  
 - [ ] woody.mortality  
 - [ ] woody.mortality_ag  
 - [ ] woody.mortality_root  
 - [ ] BNPP_root  
 - [ ] BNPP_root_coarse  
 - [ ] BNPP_root_fine  
 - [ ] BNPP_root.turnover_fine  
 - [ ] R_eco  
 - [ ] R_eco_cum  
 - [ ] R_auto  
 - [ ] R_auto_ag  
 - [ ] R_auto_wood  
 - [ ] R_auto_foliage  
 - [ ] R_auto_root  
 - [ ] R_soil  
 - [ ] R_het_soil  
 - [ ] R_het_litter  
 - [ ] R_het_deadwood  
 - [ ] R_het_ag  
 - [ ] R_het  
 - [ ] delta.total.ecosystem  
 - [ ] delta.total.ecosystem_2  
 - [ ] delta.biomass  
 - [ ] delta.agb  
 - [ ] delta.biomass_root  
 - [ ] delta.biomass_root_coarse  
 - [ ] delta.biomass_root_fine  
 - [ ] delta.deadwood  
 - [ ] delta.deadwood_standing  
 - [ ] delta.deadwood_down  
 - [ ] delta.litter  
 - [ ] delta.organic.layer  
 - [ ] delta.O.horizon  
 - [ ] delta.soil  
 - [ ] total.ecosystem  
 - [ ] total.ecosystem_2  
 - [ ] biomass  
 - [ ] biomass_ag  
 - [ ] biomass_ag_woody  
 - [ ] biomass_ag_foliage  
 - [ ] biomass_ag_understory  
 - [ ] biomass_root  
 - [ ] biomass_root_coarse  
 - [ ] biomass_root_fine  
 - [ ] deadwood  
 - [ ] deadwood_standing  
 - [ ] deadwood_down  
 - [ ] litter  
 - [ ] organic.layer  
 - [ ] O.horizon  
 - [ ] soil  
 - [ ] stand.density  
 - [ ] LAI  
 - [ ] leaf_pC  
 - [ ] leaf2N  
 - [ ] leaf_pN  
 - [ ] foliage_pN  
 - [ ] leaf_pCa  
 - [ ] leaf_pK  
 - [ ] leaf_pMg  
 - [ ] leaf_pP  
 - [ ] stem_pC  
 - [ ] stem_pN  
 - [ ] root_pN  
 - [ ] root_pC  
 - [ ] soil_pC  
 - [ ] soil2N  
 - [ ] N.mineralization  
 - [ ] max.diameter  
 - [ ] min.diameter  
 - [ ] max.diameter_branch  
 - [ ] min.diameter_branch  
 - [ ] max.diameter_twig  
 - [ ] max.diameter_root  
 - [ ] min.diameter_root  
 - [ ] min.diameter_liana  
 - [ ] min.height  
 - [ ] max.height  
 - [ ] min.length  
 - [ ] min.depth  
 - [ ] u.star  
 - [ ] stem.level  
 - [ ] include.recruitment

**Comment by teixeirak** [comment]
I see NPP_woody in this list, but it's also in [this table](https://github.com/forc-db/IPCC-EFDB-integration/blob/main/doc/manuscript/figures_tables/C_variables_order_template.csv). Ditto for ANPP_woody.

**Comment by teixeirak** [comment]
> ANPP_woody_branch

Not sure what to do about this one. IPCC wants it, but it's a minor variable and I'd prefer not to bog down the figure and table with it. I'll come back to this.

**Comment by ValentineHerr** [comment]
> I see NPP_woody in this list, but it's also in [this table](https://github.com/forc-db/IPCC-EFDB-integration/blob/main/doc/manuscript/figures_tables/C_variables_order_template.csv). Ditto for ANPP_woody.

oops.. sorry, I'll see what happened there.

**Comment by teixeirak** [comment]
> I see NPP_woody in this list, but it's also in [this table](https://github.com/forc-db/IPCC-EFDB-integration/blob/main/doc/manuscript/figures_tables/C_variables_order_template.csv). Ditto for ANPP_woody.

Actually, I think that's a list of all variables. 

Those of interest to IPCC are in the `provide.to.IPCC` field of [this file](https://github.com/forc-db/IPCC-EFDB-integration/blob/main/doc/ForC-EFDB_mapping/ForC_variables_mapping.csv). 

There's some discrepancy between the ones that IPCC wants and the ones I wanted to show in the figure & table. I need to think about that.

**Comment by teixeirak** [comment]
What would be helpful is to get a list of the variables not in [this table](https://github.com/forc-db/IPCC-EFDB-integration/blob/main/doc/manuscript/figures_tables/C_variables_order_template.csv) but flagged in the `provide.to.IPCC` field of [this file](https://github.com/forc-db/IPCC-EFDB-integration/blob/main/doc/ForC-EFDB_mapping/ForC_variables_mapping.csv).

**Comment by teixeirak** [comment]
I guess we need to either list them all or create an "other variables" category.

**Comment by ValentineHerr** [comment]
FYI, edited the list. 
It now only shows the ones that are not in the C_variables_order_template.csv file.

We look into your other comments now.

**Comment by ValentineHerr** [comment]
wait.... still does not seem right

**Comment by ValentineHerr** [comment]
> I guess we need to either list them all or create an "other variables" category.

The main concern is space in the C_variable_mapping.png diagram?

**Comment by teixeirak** [comment]
Here's my list of what to do with each (I'll edit this gradually):


 - [ ] ANPP_woody_stem  - change variable mapping figure to read ANPP_woody(_stem) (**KAT**), include with ANPP_woody in table (list as "ANPP_woody(_stem)" or "ANPP_woody / ANPP_woody_stem")
 - [ ] ANPP_woody_branch  
 - [ ] ANPP_litterfall_1  
 - [ ] ANPP_litterfall_2  
 - [ ] BNPP_root  
 - [ ] delta.total.ecosystem_2  
 - [ ] total.ecosystem_2  
 - [ ] biomass_ag_understory  
 - [ ] stem_pC

**Comment by teixeirak** [comment]
@ValentineHerr , I think the above list is good now.

**Comment by teixeirak** [comment]
Replicating the list above so that I can check off my edits:

Here's my list of what to do with each (I'll edit this gradually):


 - [ ] ANPP_woody_stem  - change variable mapping figure to read ANPP_woody(_stem) (**KAT**), add as new row after ANPP_woody in table 
 - [ ] ANPP_woody_branch  (243 records in ForC) - add footnote on figure (**KAT**), add as new row after ANPP_woody_stem in table 
 - [ ] ANPP_litterfall_1  - edit names on mapping figure under both foliage and litter (**KAT**), include in table with NPP_litter, renaming row as "ANPP_litter / NPP_litter" 
 - [ ] ANPP_litterfall_2  - same as above
 - [ ] BNPP_root  - add to table as new row (above BNPP_root_fine)
 - [ ] delta.total.ecosystem_2  (0 records in ForC)- add footnote on figure (**KAT**), in table (before soil C) add new header row "Total Ecosystem C", and place this underneath (after total.ecosystem_2). 
 - [ ] total.ecosystem_2  (64 records in ForC)- add footnote on figure (**KAT**), in table (before soil C) add new header row "Total Ecosystem C", and place this underneath (before delta.total.ecosystem_2). 
 - [ ] biomass_ag_understory  - add footnote on figure (**KAT**), include with biomass_ag (no edit to variable name in table)
 - [ ] stem_pC  (9 records in ForC) - add footnote on figure (**KAT**),  add as new row at end of "aboveground biomass" category

**Comment by ValentineHerr** [comment]
let me know when you've pushed your edits

**Comment by teixeirak** [comment]
> For the variables that needs their own rows, if you add them in that C_variables_order_template.csv file, they will be pulled in the summary table.

Oops, I missed this. Will do it now.

**Comment by teixeirak** [comment]
when multiple variables should be combined in the same row, should I separate with "/"? It looks like that's what we did for SOC/ SOM.

**Comment by ValentineHerr** [comment]
For now add a row but repeat the value in the third column (`variable`).

**Comment by teixeirak** [comment]
Oh, so `variable` is what's displayed? (I'll need to adjust what I've been doing.)

**Comment by ValentineHerr** [comment]
> Oh, so `variable` is what's displayed? (I'll need to adjust what I've been doing.)
yes.
I use that table to have an easy way to order he variables in the way you wanted, and also to display prettier names
